# Generated by Django 4.1.7 on 2023-03-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Genre", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ComName", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("WebtoonID", models.TextField()),
                ("Title", models.TextField()),
                ("Description", models.TextField()),
                ("Age", models.IntegerField()),
                ("Stars", models.FloatField()),
                ("End", models.BooleanField()),
                ("Round", models.IntegerField()),
                ("WebLink", models.TextField()),
                ("CharLink", models.TextField()),
                ("BackLink", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WebPlat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Plat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Webtoon.platform",
                    ),
                ),
                (
                    "Web",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Webtoon.webtoon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebGen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Gen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Webtoon.genre",
                    ),
                ),
                (
                    "Web",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Webtoon.webtoon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebAu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Au",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Webtoon.author",
                    ),
                ),
                (
                    "Web",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Webtoon.webtoon",
                    ),
                ),
            ],
        ),
    ]
